### ISSUE TITLE
Dont push node_modules to repo

### ISSUE THREAD

**Issue by codencolors** [codencolors/training_expressjs#2]
Target: https://github.com/codencolors/training_expressjs/tree/master/Login_Password_API/nodejs-api-auth

Since dev enviroment can differ on different machines so we don't push the dependencies to remote repo.

Add the **node_modules** to **.gitignore** then push the changes.

Also delete the **node_modules** from remote repo using the following command

- git rm -r --cached some-directory
- git commit -m 'Remove the now ignored directory "some-directory"'
- git push origin master

Ref: https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

**Comment by adarsht756** [comment]
Please check repo again, I have fixed the issues you raised

**Comment by adarsht756** [comment]
I am extremely sorry sir, by mistake I closed issue,this won't happen again
