### ISSUE TITLE
Add upload folder to .gitignore

### ISSUE THREAD

**Issue by codencolors** [codencolors/training_expressjs#5]
https://github.com/codencolors/training_expressjs/tree/master/upload_image_API

Don't push images to the remote repo until they are part of core functionality. 

Also if **upload** directory can be created dynamically then add it to .gitignore, if not, and it is required for the proper functioning of the application then add the content inside **upload** directory to .gitignore.

**Comment by adarsht756** [comment]
Sir, I have fixed issue you raised, please check again and review.
